// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path";
import { defineConfig } from "prisma/config";

const railwayVolumePath = process.env["RAILWAY_VOLUME_MOUNT_PATH"];
const databaseUrl = railwayVolumePath
  ? `file:${path.posix.join(railwayVolumePath, "dev.db")}`
  : process.env["DATABASE_URL"] || "file:./dev.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Keep Prisma Migrate on the exact same persistent database as the app.
    url: databaseUrl,
  },
});
